new: removed direct access to hook commands in favor of the ``git-hooks add HOOK [HOOK OPTIONS...]`` model.

diff --git a/bin/git-hooks b/bin/git-hooks
--- a/bin/git-hooks
+++ b/bin/git-hooks
@@ -87,12 +87,13 @@ function make_git_hooks_inited() {
     fi
 }
 
+
+##
+# hook_name should have been set !
 function init_action() {
 
-    local hook_name md5salt md5 name l c hook_src
-
-    hook_name="$1"
-    md5salt="$2"
+    local md5salt md5 name l c hook_src
+    md5salt="$1"
 
     md5=$(echo "$md5salt" | md5sum | cut -c 1-8 )
     name="${hook_name}_${host}_${md5}"
@@ -119,91 +120,49 @@ function init_action() {
 
 }
 
-function git_hooks_follow() {
-    local hook_name
 
-    hook_name="sync-workdir"
+git_hooks_add() {
 
-    ## XXXvlab: remove reverse_host !
-    usage="$exname follow BRANCH HOST:DIR REVERSE_HOST"
+    export hook_name="$1"
+    shift
 
-    if [ "$#" != 3  ]; then
-        echo "Wrong number of arguments"
+    hook_files="$(echo "$githooks_base/hooks/"*.hook)"
+    if [ "$hook_files" == "$githooks_base/hooks/*.hook" ]; then
+        echo "No hook available. Else yor hook dir is empty, or "
+        echo "hook files are not correctly named."
+        echo "    -> Your hooks should be placed and named as follows:"
+        echo "       '$githooks_base/hooks/*.hook'"
+        exit 1
+    fi
+
+    if [ -z "$hook_name" ]; then
+        usage="$exname add HOOK [HOOK-OPTIONS...]"
+        echo "You should provide a hook name."
+        echo
+        echo "These are the available hooks:"
+        for hook_file in $hook_files; do
+            echo " - $(basename "$hook_file" .hook)"
+        done
+        echo
         echo "usage: $usage"
         exit 1
     fi
 
-    branch=$1
-    hostdir=$2
-    revhost=$3
-
-    host=$(echo $2 | cut -f 1 -d ":")
-    dir=$(echo $2 | cut -f 2- -d ":")
-
-    make_ssh_connection_work "$host" || exit 1
-
-    md5=$(echo "$dir" | md5sum | cut -c 1-8 )
-    name="${hook_name}_${host}_${md5}"
-
-    make_git_hooks_inited || exit 1
-
-    l="$gitdir/hooks/post-receive.d/$name.hook"
-    c="$gitdir/hooks/post-receive.d/$name.conf"
-
-    if [ -e "$l" ]; then
-        echo "File '$l' already exists."
+    hook_file=$githooks_base/hooks/$hook_name.hook
+    if ! [ -e "$hook_file" ]; then
+        echo "Hook file '$hook_file' not found."
+        echo "No hook '$1' available."
         exit 1
     fi
 
-    ln -sn "$githooks_base/hooks/sync-workdir.hook" "$l"
-    cat <<EOF > "$c"
-
-HOST="$host"
-DISTANT_REPO_DIR="$dir"
-TARGET_BRANCH="$branch"
-
-## XXXvlab: find another solution
-SOURCE_REPO_FOR_TARGET_REPO="$revhost"
-
-EOF
-
-}
-export -f git_hooks_follow
-
-
-
-function git_hooks_release() {
-    local hook_name
-
-    hook_name="release-on-tag"
-    ## XXXvlab: remove reverse_host !
-    usage="$exname release TAG_REGEX HOST:DIR"
-
-    if [ "$#" != 2  ]; then
-        echo "Wrong number of arguments"
-        echo "usage: $usage"
-        exit 1
-    fi
-
-    tag_regex=$1
-    hostdir=$2
-
-    host=$(echo $hostdir | cut -f 1 -d ":")
-    dir=$(echo $hostdir | cut -f 2- -d ":")
-
-    make_ssh_connection_work "$host" || exit 1
     make_git_hooks_inited || exit 1
 
-    init_action "$hook_name" "$dir" <<EOF
+    command_prefix="$exname add $hook_name"
+    . "$hook_file"
 
-HOST="$host"
-DISTANT_REPO_DIR="$dir"
-TARGET_TAG_REGEX="$tag_regex"
-
-EOF
+    install "$@"
 
 }
-export -f git_hooks_release
 
 
 ##
